[github-actions] - checking file size

diff --git a/.github/workflows/second-react-workflow.yml b/.github/workflows/second-react-workflow.yml
--- a/.github/workflows/second-react-workflow.yml
+++ b/.github/workflows/second-react-workflow.yml
@@ -25,14 +25,23 @@ jobs:
         run: |
           git fetch origin ${GITHUB_BASE_REF}
           git fetch origin ${GITHUB_HEAD_REF}
-          git diff --diff-filter=A --no-renames --name-only origin/develop origin/main \
+          git diff --diff-filter=A --no-renames --name-only origin/${GITHUB_BASE_REF} origin/${GITHUB_HEAD_REF} \
+          | grep -v '\.mps$' \
           | while read FILE; do
               if ! git lfs ls-files "$FILE" &> /dev/null && [ $(wc -c < "$FILE") -gt $MAX_FILE_SIZE ]; then
                 MAX_FILE_SIZE_MB=$((MAX_FILE_SIZE / 1048576))
                 echo "::error file=$FILE::File size exceeds ${MAX_FILE_SIZE_MB} MB limit"
                 exit 1
               fi
-              if ! git lfs ls-files "$FILE" &> /dev/null && [ $(wc -c < "$FILE") -lte $MIN_FILE_SIZE ]; then
+              if [ $(wc -c < "$FILE") -le 0 ]; then
+                echo "::error file=$FILE::File is empty"
+                exit 1
+              fi
+          done
+          git diff --diff-filter=A --no-renames --name-only origin/${GITHUB_BASE_REF} origin/${GITHUB_HEAD_REF} \
+          | grep -v '.mps$' \
+          | while read FILE; do
+              if [ $(wc -c < "$FILE") -le 0 ]; then
                 echo "::error file=$FILE::File is empty"
                 exit 1
               fi
