Update second-react-workflow.yml

diff --git a/.github/workflows/second-react-workflow.yml b/.github/workflows/second-react-workflow.yml
--- a/.github/workflows/second-react-workflow.yml
+++ b/.github/workflows/second-react-workflow.yml
@@ -1,9 +1,8 @@
 name: Activity types workflow
 on:
-  pull_request:
-    types:
-      - opened
-      - edited
+  push:
+    branches: 
+    - develop
   workflow_dispatch:
 env:
   MAX_FILE_SIZE: 1048576 # 1 MB
@@ -21,24 +20,9 @@ jobs:
         run: npm run build
       - name: Deploy
         run: echo "Deploying..."
-      - name: Check file size
+      - name: Check for zero-length models
         run: |
-          git fetch origin ${GITHUB_BASE_REF}
-          git fetch origin ${GITHUB_HEAD_REF}
-          git diff --diff-filter=A --no-renames --name-only origin/${GITHUB_BASE_REF} origin/${GITHUB_HEAD_REF} \
-          | grep -v '\.mps$' \
-          | while read FILE; do
-              if ! git lfs ls-files "$FILE" &> /dev/null && [ $(wc -c < "$FILE") -gt $MAX_FILE_SIZE ]; then
-                MAX_FILE_SIZE_MB=$((MAX_FILE_SIZE / 1048576))
-                echo "::error file=$FILE::File size exceeds ${MAX_FILE_SIZE_MB} MB limit"
-                exit 1
-              fi
-          done
-          git diff --diff-filter=A --no-renames --name-only origin/${GITHUB_BASE_REF} origin/${GITHUB_HEAD_REF} \
-          | grep '\.mps$' \
-          | while read FILE; do
-              if [ $(wc -w < $file) -le 0 ]; then
-                echo "::error file=$FILE::File is empty"
-                exit 1
-              fi
-          done
+          found=0
+          find -name '*.mps' -size 0 | while read FILE; do echo "::error file=$FILE::File is empty"; found=1; done
+          exit $found
+          shell: bash
